# Copyright (c) DataLab Platform Developers, BSD 3-Clause license, see LICENSE file.

"""Renderer-independent graphical annotations."""

from sigima.objects.annotations.legacy_plotpy import (
    LegacyPlotPyMigrationReport,
    legacy_plotpy_payload_to_annotations,
    migrate_legacy_plotpy_annotations,
)
from sigima.objects.annotations.model import (
    AnnotationKind,
    AnnotationLabel,
    AnnotationStyle,
    Axis,
    CircleAnnotation,
    CoordinateSpace,
    CursorAnnotation,
    CursorOrientation,
    EllipseAnnotation,
    FillStyle,
    GraphicalAnnotation,
    MarkerStyle,
    PointAnnotation,
    PolygonAnnotation,
    PolylineAnnotation,
    RangeAnnotation,
    RectangleAnnotation,
    SegmentAnnotation,
    StrokeStyle,
    TextAnchor,
    TextAnnotation,
    TextStyle,
)
from sigima.objects.annotations.serialization import (
    ANNOTATION_FORMAT,
    ANNOTATION_VERSION,
    annotation_from_dict,
    annotation_to_dict,
    is_graphical_annotation_dict,
)
from sigima.objects.annotations.transform import (
    AnnotationTransformError,
    flip_annotation_horizontally,
    flip_annotation_vertically,
    rotate_annotation,
    scale_annotation,
    transform_annotation,
    translate_annotation,
    transpose_annotation,
)

__all__ = [
    "ANNOTATION_FORMAT",
    "ANNOTATION_VERSION",
    "AnnotationKind",
    "AnnotationLabel",
    "AnnotationStyle",
    "AnnotationTransformError",
    "Axis",
    "CircleAnnotation",
    "CoordinateSpace",
    "CursorAnnotation",
    "CursorOrientation",
    "EllipseAnnotation",
    "FillStyle",
    "GraphicalAnnotation",
    "LegacyPlotPyMigrationReport",
    "MarkerStyle",
    "PointAnnotation",
    "PolygonAnnotation",
    "PolylineAnnotation",
    "RangeAnnotation",
    "RectangleAnnotation",
    "SegmentAnnotation",
    "StrokeStyle",
    "TextAnchor",
    "TextAnnotation",
    "TextStyle",
    "annotation_from_dict",
    "annotation_to_dict",
    "flip_annotation_horizontally",
    "flip_annotation_vertically",
    "is_graphical_annotation_dict",
    "legacy_plotpy_payload_to_annotations",
    "migrate_legacy_plotpy_annotations",
    "rotate_annotation",
    "scale_annotation",
    "transform_annotation",
    "translate_annotation",
    "transpose_annotation",
]
